
version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
      - 9000:9000
    volumes:
      - ./nginx:/etc/nginx/templates
    depends_on:
      - minio
      - postgrest
      - opensearch

  postgrest:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgresql://${PG_API_USER}:${PG_API_PASSWORD}@postgres:5432/insight
      PGRST_DB_SCHEMAS: public
      PGRST_JWT_SECRET: "@/run/secrets/jwk"
      PGRST_JWT_ROLE_CLAIM_KEY: .resource_access.insight_user.roles[0]
      PGRST_DB_ANON_ROLE: external_anonymous
    secrets:
      - jwk
    depends_on:
      - postgres

  worker:
    build: worker
    command: watchmedo auto-restart -d=/usr/local/lib/python3.11/site-packages/insight_worker -p="*.py" -R insight-worker -- process-messages
    environment:
      API_ENDPOINT: http://nginx
      OAUTHLIB_INSECURE_TRANSPORT: 1
      AUTH_TOKEN_ENDPOINT: ${AUTH_TOKEN_ENDPOINT}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      TIKA_URI: http://tika:9998/tika
      POSTGRES_URI: postgresql://${PG_WORKER_USER}:${PG_WORKER_PASSWORD}@postgres:5432/insight
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      STORAGE_SECURE: ${STORAGE_SECURE}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
    volumes:
      - ./worker/insight_worker:/usr/local/lib/python3.11/site-packages/insight_worker
    depends_on:
      - tika
      - postgres
      - nginx

  tika:
    image: apache/tika

  opensearch:
    image: opensearchproject/opensearch
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      #- ./opensearch/security.yml:/usr/share/opensearch/config/opensearch-security/config.yml

  postgres:
    build: postgres
    environment:
      POSTGRES_USER: insight
      POSTGRES_PASSWORD: insight
      PG_API_USER: ${PG_API_USER}
      PG_API_PASSWORD: ${PG_API_PASSWORD}
      PG_WORKER_USER: ${PG_WORKER_USER}
      PG_WORKER_PASSWORD: ${PG_WORKER_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      STORAGE_SECURE: ${STORAGE_SECURE}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    depends_on:
      - minio

  minio:
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /data/${STORAGE_BUCKET} && minio server /data'
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    volumes:
      - minio-data:/data

  cli:
    build: cli
    environment:
      OAUTHLIB_INSECURE_TRANSPORT: 1
    volumes:
      - ./cli/insight_cli:/usr/local/lib/python3.11/site-packages/insight_cli
      - ./data:/root/data

secrets:
   jwk:
     file: .jwk

volumes:
  minio-data: {}
  postgres-data: {}
  opensearch-data: {}

