
version: '3'

services:
  gateway:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./templates:/etc/nginx/templates
      - pagestreams:/pagestreams

  api:
    image: postgrest/postgrest
    environment:
      PGRST_DB_SCHEMAS: insight
      PGRST_JWT_SECRET: "@/run/secrets/jwk"
      PGRST_JWT_ROLE_CLAIM_KEY: .realm_access.roles[2]
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    env_file:
      - .env
    secrets:
      - jwk
    depends_on:
      - database

  #api-documentation:
    #image: swaggerapi/swagger-ui
    #ports:
      #- "8080:8080"
    #environment:
      #API_URL: http://api:3000/

  ingest:
    build: ingest
    env_file:
      - .env

  database:
    image: postgres
    environment:
      POSTGRES_USER: insight
      POSTGRES_PASSWORD: insight
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

secrets:
   jwk:
     file: .jwk

volumes:
  pgdata: {}
  pagestreams: {}

