
version: '3'

services:
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://insight:insight@db:5432/insight
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: insight
      POSTGRES_PASSWORD: insight
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
